# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files (x86)\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files (x86)\CMake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\Git\Physics

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\Git\Physics

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files (x86)\CMake\bin\cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files (x86)\CMake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Git\Physics\CMakeFiles D:\Git\Physics\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Git\Physics\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Exe

# Build rule for target.
Exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 Exe
.PHONY : Exe

# fast build rule for target.
Exe/fast:
	$(MAKE) -f CMakeFiles\Exe.dir\build.make CMakeFiles/Exe.dir/build
.PHONY : Exe/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) -f CMakeFiles\run.dir\build.make CMakeFiles/run.dir/build
.PHONY : run/fast

src/Constraint.obj: src/Constraint.cpp.obj
.PHONY : src/Constraint.obj

# target to build an object file
src/Constraint.cpp.obj:
	$(MAKE) -f CMakeFiles\Exe.dir\build.make CMakeFiles/Exe.dir/src/Constraint.cpp.obj
.PHONY : src/Constraint.cpp.obj

src/Constraint.i: src/Constraint.cpp.i
.PHONY : src/Constraint.i

# target to preprocess a source file
src/Constraint.cpp.i:
	$(MAKE) -f CMakeFiles\Exe.dir\build.make CMakeFiles/Exe.dir/src/Constraint.cpp.i
.PHONY : src/Constraint.cpp.i

src/Constraint.s: src/Constraint.cpp.s
.PHONY : src/Constraint.s

# target to generate assembly for a file
src/Constraint.cpp.s:
	$(MAKE) -f CMakeFiles\Exe.dir\build.make CMakeFiles/Exe.dir/src/Constraint.cpp.s
.PHONY : src/Constraint.cpp.s

src/Elastic.obj: src/Elastic.cpp.obj
.PHONY : src/Elastic.obj

# target to build an object file
src/Elastic.cpp.obj:
	$(MAKE) -f CMakeFiles\Exe.dir\build.make CMakeFiles/Exe.dir/src/Elastic.cpp.obj
.PHONY : src/Elastic.cpp.obj

src/Elastic.i: src/Elastic.cpp.i
.PHONY : src/Elastic.i

# target to preprocess a source file
src/Elastic.cpp.i:
	$(MAKE) -f CMakeFiles\Exe.dir\build.make CMakeFiles/Exe.dir/src/Elastic.cpp.i
.PHONY : src/Elastic.cpp.i

src/Elastic.s: src/Elastic.cpp.s
.PHONY : src/Elastic.s

# target to generate assembly for a file
src/Elastic.cpp.s:
	$(MAKE) -f CMakeFiles\Exe.dir\build.make CMakeFiles/Exe.dir/src/Elastic.cpp.s
.PHONY : src/Elastic.cpp.s

src/FPSCounter.obj: src/FPSCounter.cpp.obj
.PHONY : src/FPSCounter.obj

# target to build an object file
src/FPSCounter.cpp.obj:
	$(MAKE) -f CMakeFiles\Exe.dir\build.make CMakeFiles/Exe.dir/src/FPSCounter.cpp.obj
.PHONY : src/FPSCounter.cpp.obj

src/FPSCounter.i: src/FPSCounter.cpp.i
.PHONY : src/FPSCounter.i

# target to preprocess a source file
src/FPSCounter.cpp.i:
	$(MAKE) -f CMakeFiles\Exe.dir\build.make CMakeFiles/Exe.dir/src/FPSCounter.cpp.i
.PHONY : src/FPSCounter.cpp.i

src/FPSCounter.s: src/FPSCounter.cpp.s
.PHONY : src/FPSCounter.s

# target to generate assembly for a file
src/FPSCounter.cpp.s:
	$(MAKE) -f CMakeFiles\Exe.dir\build.make CMakeFiles/Exe.dir/src/FPSCounter.cpp.s
.PHONY : src/FPSCounter.cpp.s

src/Main.obj: src/Main.cpp.obj
.PHONY : src/Main.obj

# target to build an object file
src/Main.cpp.obj:
	$(MAKE) -f CMakeFiles\Exe.dir\build.make CMakeFiles/Exe.dir/src/Main.cpp.obj
.PHONY : src/Main.cpp.obj

src/Main.i: src/Main.cpp.i
.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) -f CMakeFiles\Exe.dir\build.make CMakeFiles/Exe.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s
.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) -f CMakeFiles\Exe.dir\build.make CMakeFiles/Exe.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/Polygon.obj: src/Polygon.cpp.obj
.PHONY : src/Polygon.obj

# target to build an object file
src/Polygon.cpp.obj:
	$(MAKE) -f CMakeFiles\Exe.dir\build.make CMakeFiles/Exe.dir/src/Polygon.cpp.obj
.PHONY : src/Polygon.cpp.obj

src/Polygon.i: src/Polygon.cpp.i
.PHONY : src/Polygon.i

# target to preprocess a source file
src/Polygon.cpp.i:
	$(MAKE) -f CMakeFiles\Exe.dir\build.make CMakeFiles/Exe.dir/src/Polygon.cpp.i
.PHONY : src/Polygon.cpp.i

src/Polygon.s: src/Polygon.cpp.s
.PHONY : src/Polygon.s

# target to generate assembly for a file
src/Polygon.cpp.s:
	$(MAKE) -f CMakeFiles\Exe.dir\build.make CMakeFiles/Exe.dir/src/Polygon.cpp.s
.PHONY : src/Polygon.cpp.s

src/Rigid.obj: src/Rigid.cpp.obj
.PHONY : src/Rigid.obj

# target to build an object file
src/Rigid.cpp.obj:
	$(MAKE) -f CMakeFiles\Exe.dir\build.make CMakeFiles/Exe.dir/src/Rigid.cpp.obj
.PHONY : src/Rigid.cpp.obj

src/Rigid.i: src/Rigid.cpp.i
.PHONY : src/Rigid.i

# target to preprocess a source file
src/Rigid.cpp.i:
	$(MAKE) -f CMakeFiles\Exe.dir\build.make CMakeFiles/Exe.dir/src/Rigid.cpp.i
.PHONY : src/Rigid.cpp.i

src/Rigid.s: src/Rigid.cpp.s
.PHONY : src/Rigid.s

# target to generate assembly for a file
src/Rigid.cpp.s:
	$(MAKE) -f CMakeFiles\Exe.dir\build.make CMakeFiles/Exe.dir/src/Rigid.cpp.s
.PHONY : src/Rigid.cpp.s

src/Vertex.obj: src/Vertex.cpp.obj
.PHONY : src/Vertex.obj

# target to build an object file
src/Vertex.cpp.obj:
	$(MAKE) -f CMakeFiles\Exe.dir\build.make CMakeFiles/Exe.dir/src/Vertex.cpp.obj
.PHONY : src/Vertex.cpp.obj

src/Vertex.i: src/Vertex.cpp.i
.PHONY : src/Vertex.i

# target to preprocess a source file
src/Vertex.cpp.i:
	$(MAKE) -f CMakeFiles\Exe.dir\build.make CMakeFiles/Exe.dir/src/Vertex.cpp.i
.PHONY : src/Vertex.cpp.i

src/Vertex.s: src/Vertex.cpp.s
.PHONY : src/Vertex.s

# target to generate assembly for a file
src/Vertex.cpp.s:
	$(MAKE) -f CMakeFiles\Exe.dir\build.make CMakeFiles/Exe.dir/src/Vertex.cpp.s
.PHONY : src/Vertex.cpp.s

src/World.obj: src/World.cpp.obj
.PHONY : src/World.obj

# target to build an object file
src/World.cpp.obj:
	$(MAKE) -f CMakeFiles\Exe.dir\build.make CMakeFiles/Exe.dir/src/World.cpp.obj
.PHONY : src/World.cpp.obj

src/World.i: src/World.cpp.i
.PHONY : src/World.i

# target to preprocess a source file
src/World.cpp.i:
	$(MAKE) -f CMakeFiles\Exe.dir\build.make CMakeFiles/Exe.dir/src/World.cpp.i
.PHONY : src/World.cpp.i

src/World.s: src/World.cpp.s
.PHONY : src/World.s

# target to generate assembly for a file
src/World.cpp.s:
	$(MAKE) -f CMakeFiles\Exe.dir\build.make CMakeFiles/Exe.dir/src/World.cpp.s
.PHONY : src/World.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... run
	@echo ... Exe
	@echo ... src/Constraint.obj
	@echo ... src/Constraint.i
	@echo ... src/Constraint.s
	@echo ... src/Elastic.obj
	@echo ... src/Elastic.i
	@echo ... src/Elastic.s
	@echo ... src/FPSCounter.obj
	@echo ... src/FPSCounter.i
	@echo ... src/FPSCounter.s
	@echo ... src/Main.obj
	@echo ... src/Main.i
	@echo ... src/Main.s
	@echo ... src/Polygon.obj
	@echo ... src/Polygon.i
	@echo ... src/Polygon.s
	@echo ... src/Rigid.obj
	@echo ... src/Rigid.i
	@echo ... src/Rigid.s
	@echo ... src/Vertex.obj
	@echo ... src/Vertex.i
	@echo ... src/Vertex.s
	@echo ... src/World.obj
	@echo ... src/World.i
	@echo ... src/World.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

