# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files (x86)\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files (x86)\CMake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\Source\Physics

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\Source\Physics

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files (x86)\CMake\bin\cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files (x86)\CMake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Source\Physics\CMakeFiles D:\Source\Physics\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Source\Physics\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Physics

# Build rule for target.
Physics: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 Physics
.PHONY : Physics

# fast build rule for target.
Physics/fast:
	$(MAKE) -f CMakeFiles\Physics.dir\build.make CMakeFiles/Physics.dir/build
.PHONY : Physics/fast

src/Constraint.obj: src/Constraint.cpp.obj

.PHONY : src/Constraint.obj

# target to build an object file
src/Constraint.cpp.obj:
	$(MAKE) -f CMakeFiles\Physics.dir\build.make CMakeFiles/Physics.dir/src/Constraint.cpp.obj
.PHONY : src/Constraint.cpp.obj

src/Constraint.i: src/Constraint.cpp.i

.PHONY : src/Constraint.i

# target to preprocess a source file
src/Constraint.cpp.i:
	$(MAKE) -f CMakeFiles\Physics.dir\build.make CMakeFiles/Physics.dir/src/Constraint.cpp.i
.PHONY : src/Constraint.cpp.i

src/Constraint.s: src/Constraint.cpp.s

.PHONY : src/Constraint.s

# target to generate assembly for a file
src/Constraint.cpp.s:
	$(MAKE) -f CMakeFiles\Physics.dir\build.make CMakeFiles/Physics.dir/src/Constraint.cpp.s
.PHONY : src/Constraint.cpp.s

src/Elastic.obj: src/Elastic.cpp.obj

.PHONY : src/Elastic.obj

# target to build an object file
src/Elastic.cpp.obj:
	$(MAKE) -f CMakeFiles\Physics.dir\build.make CMakeFiles/Physics.dir/src/Elastic.cpp.obj
.PHONY : src/Elastic.cpp.obj

src/Elastic.i: src/Elastic.cpp.i

.PHONY : src/Elastic.i

# target to preprocess a source file
src/Elastic.cpp.i:
	$(MAKE) -f CMakeFiles\Physics.dir\build.make CMakeFiles/Physics.dir/src/Elastic.cpp.i
.PHONY : src/Elastic.cpp.i

src/Elastic.s: src/Elastic.cpp.s

.PHONY : src/Elastic.s

# target to generate assembly for a file
src/Elastic.cpp.s:
	$(MAKE) -f CMakeFiles\Physics.dir\build.make CMakeFiles/Physics.dir/src/Elastic.cpp.s
.PHONY : src/Elastic.cpp.s

src/Polygon.obj: src/Polygon.cpp.obj

.PHONY : src/Polygon.obj

# target to build an object file
src/Polygon.cpp.obj:
	$(MAKE) -f CMakeFiles\Physics.dir\build.make CMakeFiles/Physics.dir/src/Polygon.cpp.obj
.PHONY : src/Polygon.cpp.obj

src/Polygon.i: src/Polygon.cpp.i

.PHONY : src/Polygon.i

# target to preprocess a source file
src/Polygon.cpp.i:
	$(MAKE) -f CMakeFiles\Physics.dir\build.make CMakeFiles/Physics.dir/src/Polygon.cpp.i
.PHONY : src/Polygon.cpp.i

src/Polygon.s: src/Polygon.cpp.s

.PHONY : src/Polygon.s

# target to generate assembly for a file
src/Polygon.cpp.s:
	$(MAKE) -f CMakeFiles\Physics.dir\build.make CMakeFiles/Physics.dir/src/Polygon.cpp.s
.PHONY : src/Polygon.cpp.s

src/Rigid.obj: src/Rigid.cpp.obj

.PHONY : src/Rigid.obj

# target to build an object file
src/Rigid.cpp.obj:
	$(MAKE) -f CMakeFiles\Physics.dir\build.make CMakeFiles/Physics.dir/src/Rigid.cpp.obj
.PHONY : src/Rigid.cpp.obj

src/Rigid.i: src/Rigid.cpp.i

.PHONY : src/Rigid.i

# target to preprocess a source file
src/Rigid.cpp.i:
	$(MAKE) -f CMakeFiles\Physics.dir\build.make CMakeFiles/Physics.dir/src/Rigid.cpp.i
.PHONY : src/Rigid.cpp.i

src/Rigid.s: src/Rigid.cpp.s

.PHONY : src/Rigid.s

# target to generate assembly for a file
src/Rigid.cpp.s:
	$(MAKE) -f CMakeFiles\Physics.dir\build.make CMakeFiles/Physics.dir/src/Rigid.cpp.s
.PHONY : src/Rigid.cpp.s

src/Vertex.obj: src/Vertex.cpp.obj

.PHONY : src/Vertex.obj

# target to build an object file
src/Vertex.cpp.obj:
	$(MAKE) -f CMakeFiles\Physics.dir\build.make CMakeFiles/Physics.dir/src/Vertex.cpp.obj
.PHONY : src/Vertex.cpp.obj

src/Vertex.i: src/Vertex.cpp.i

.PHONY : src/Vertex.i

# target to preprocess a source file
src/Vertex.cpp.i:
	$(MAKE) -f CMakeFiles\Physics.dir\build.make CMakeFiles/Physics.dir/src/Vertex.cpp.i
.PHONY : src/Vertex.cpp.i

src/Vertex.s: src/Vertex.cpp.s

.PHONY : src/Vertex.s

# target to generate assembly for a file
src/Vertex.cpp.s:
	$(MAKE) -f CMakeFiles\Physics.dir\build.make CMakeFiles/Physics.dir/src/Vertex.cpp.s
.PHONY : src/Vertex.cpp.s

src/World.obj: src/World.cpp.obj

.PHONY : src/World.obj

# target to build an object file
src/World.cpp.obj:
	$(MAKE) -f CMakeFiles\Physics.dir\build.make CMakeFiles/Physics.dir/src/World.cpp.obj
.PHONY : src/World.cpp.obj

src/World.i: src/World.cpp.i

.PHONY : src/World.i

# target to preprocess a source file
src/World.cpp.i:
	$(MAKE) -f CMakeFiles\Physics.dir\build.make CMakeFiles/Physics.dir/src/World.cpp.i
.PHONY : src/World.cpp.i

src/World.s: src/World.cpp.s

.PHONY : src/World.s

# target to generate assembly for a file
src/World.cpp.s:
	$(MAKE) -f CMakeFiles\Physics.dir\build.make CMakeFiles/Physics.dir/src/World.cpp.s
.PHONY : src/World.cpp.s

tests/FPSCounter.obj: tests/FPSCounter.cpp.obj

.PHONY : tests/FPSCounter.obj

# target to build an object file
tests/FPSCounter.cpp.obj:
	$(MAKE) -f CMakeFiles\Physics.dir\build.make CMakeFiles/Physics.dir/tests/FPSCounter.cpp.obj
.PHONY : tests/FPSCounter.cpp.obj

tests/FPSCounter.i: tests/FPSCounter.cpp.i

.PHONY : tests/FPSCounter.i

# target to preprocess a source file
tests/FPSCounter.cpp.i:
	$(MAKE) -f CMakeFiles\Physics.dir\build.make CMakeFiles/Physics.dir/tests/FPSCounter.cpp.i
.PHONY : tests/FPSCounter.cpp.i

tests/FPSCounter.s: tests/FPSCounter.cpp.s

.PHONY : tests/FPSCounter.s

# target to generate assembly for a file
tests/FPSCounter.cpp.s:
	$(MAKE) -f CMakeFiles\Physics.dir\build.make CMakeFiles/Physics.dir/tests/FPSCounter.cpp.s
.PHONY : tests/FPSCounter.cpp.s

tests/Main.obj: tests/Main.cpp.obj

.PHONY : tests/Main.obj

# target to build an object file
tests/Main.cpp.obj:
	$(MAKE) -f CMakeFiles\Physics.dir\build.make CMakeFiles/Physics.dir/tests/Main.cpp.obj
.PHONY : tests/Main.cpp.obj

tests/Main.i: tests/Main.cpp.i

.PHONY : tests/Main.i

# target to preprocess a source file
tests/Main.cpp.i:
	$(MAKE) -f CMakeFiles\Physics.dir\build.make CMakeFiles/Physics.dir/tests/Main.cpp.i
.PHONY : tests/Main.cpp.i

tests/Main.s: tests/Main.cpp.s

.PHONY : tests/Main.s

# target to generate assembly for a file
tests/Main.cpp.s:
	$(MAKE) -f CMakeFiles\Physics.dir\build.make CMakeFiles/Physics.dir/tests/Main.cpp.s
.PHONY : tests/Main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... Physics
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... src/Constraint.obj
	@echo ... src/Constraint.i
	@echo ... src/Constraint.s
	@echo ... src/Elastic.obj
	@echo ... src/Elastic.i
	@echo ... src/Elastic.s
	@echo ... src/Polygon.obj
	@echo ... src/Polygon.i
	@echo ... src/Polygon.s
	@echo ... src/Rigid.obj
	@echo ... src/Rigid.i
	@echo ... src/Rigid.s
	@echo ... src/Vertex.obj
	@echo ... src/Vertex.i
	@echo ... src/Vertex.s
	@echo ... src/World.obj
	@echo ... src/World.i
	@echo ... src/World.s
	@echo ... tests/FPSCounter.obj
	@echo ... tests/FPSCounter.i
	@echo ... tests/FPSCounter.s
	@echo ... tests/Main.obj
	@echo ... tests/Main.i
	@echo ... tests/Main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

